version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "6379:6379"

  web:
    build: .
    command:
      bash -c "rm -rIf db.sqlite3 &&
      python manage.py makemigrations &&
      python manage.py migrate --run-syncdb &&
      python manage.py initadmin &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  djangoq:
    build: .
    command: python manage.py qcluster
    volumes:
      - .:/code
    ports:
      - "8001"
    depends_on:
      - db